### PR TITLE
Maintenance

### LINKED ISSUE #14: Potential Issue with where clauses
Currently the `.where()` method will take the first parameter and put it in back ticks while making the second parameter an value for a prepared statement. This should be okay for the very most cases, but if the user does something odd it like trying to put the value first and then the column name it might not work - or worse: It works but is now SQL Injectable.

Another issues potential issue is the free choice of the operator which will be simply plugged in between. If the user puts a variable in that place it is another SQL injection potential. I think some option to limit this would be appropriate. 

Anyway the question is: what should it ideally do and what is an acceptable simplification?

### LINKED ISSUE #22: Only one order by can be handled
**Describe the Bug**
The `.order()` method on the `Query` overwrites itself and only saves the last instance. This makes it impossible to sensible write queries which require multiple order by statements. 

**To Reproduce**
`repo.query().order("x").order("y");`

**Expected behavior**
Should not throw away previous orders.

**Screenshots / Logs**
None

**Environment Information:**
 - Java Language Level : 

**Additional Context**
None

### PR DESCRIPTION
**Pull request by JanHolger**
This pull request is supposed to redesign the query building process to allow implenting other dialects aswell as fixing issues that came up in the last months.

### CODE REVIEW

File: src/main/java/org/javawebstack/orm/query/QueryCondition.java [hunk 1]
```diff
@@ -1,23 +1,41 @@
...
-import java.util.ArrayList;
 import java.util.Arrays;
 import java.util.List;
-import java.util.stream.Collectors;
-import java.util.stream.IntStream;
+import java.util.Locale;
 
 public class QueryCondition implements QueryElement {
 
+    private static final List<String> VALID_OPERATORS = Arrays.asList(
```
Comment (TimothyGillespie) [inline src/main/java/org/javawebstack/orm/query/QueryCondition.java:11]: Can we move this to a centralized information class? My suggestion would be something like `src/main/java/org/javawebstack/orm/information/QuerySyntax.java`.

I can reuse this information in tests and I can imagine it is reusable somewhere else.

I did something similiar here: https://github.com/JavaWebStack/ORM/pull/7/commits/cc4c851ed9b33fd85101fdfb3ae96f7ec3090811 (unmerged branch)

File: src/main/java/org/javawebstack/orm/query/QueryCondition.java [hunk 2]
```diff
@@ -1,23 +1,41 @@
...
+            "not like"
+    );
+
     private final Object left;
     private final String operator;
     private final Object right;
     private final boolean not;
 
     public QueryCondition(Object left, String operator, Object right, boolean not) {
+        validateOperator(operator);
```
Comment (TimothyGillespie) [inline src/main/java/org/javawebstack/orm/query/QueryCondition.java:36]: For reference: This will partially address #14

File: src/main/java/org/javawebstack/orm/query/Query.java [hunk 3]
```diff
@@ -296,59 +319,10 @@ public Query(Repo<T> repo, Class<T> model) {
         return this;
     }
 
-    public QueryString getQueryString() {
```
Comment (TimothyGillespie) [inline src/main/java/org/javawebstack/orm/query/Query.java:299]: This confuses me. Removing this should break the tests for the newly merged query test tooling, but it seems the test are running.

**Review by TimothyGillespie — COMMENTED** [review]
As it is only a draft I only gave it a cursory look. When it is ready for review, please mark request me for review, since I'm not sure if I will beinformed about any status change.

File: src/main/java/org/javawebstack/orm/query/Query.java (hunk 3 above)
Comment (JanHolger) [reply src/main/java/org/javawebstack/orm/query/Query.java:299]: I already merged the tests from master into the maintenance branch and did the necessary fixes. The replacement for this is `query.getRepo().getConnection().builder().buildQuery(query, false)` which now uses the query builder for the dialect of the connection.

File: src/main/java/org/javawebstack/orm/query/QueryCondition.java (hunk 2 above)
Comment (JanHolger) [reply src/main/java/org/javawebstack/orm/query/QueryCondition.java:36]: Why only partially? I also added a check for non-raw column names in `QueryColumn` in case you missed it (:

File: src/main/java/org/javawebstack/orm/query/QueryCondition.java (hunk 1 above)
Comment (JanHolger) [reply src/main/java/org/javawebstack/orm/query/QueryCondition.java:11]: In general I would consider static references to other classes bad practice and many other developers would probably agree. It creates dependencies and therefore often makes refactoring way harder. If we move it out of the class then i would suggest to create an enum for it which i probably should have done in the first place. This way we could even allow the enum as a parameter to the where method.

File: src/main/java/org/javawebstack/orm/query/Query.java (hunk 3 above)
Comment (TimothyGillespie) [reply src/main/java/org/javawebstack/orm/query/Query.java:299]: Makes sense. Great!

File: src/main/java/org/javawebstack/orm/query/QueryColumn.java [hunk 4]
```diff
@@ -37,4 +43,9 @@ public String toString(TableInfo info) {
         return Arrays.stream((info != null ? info.getColumnName(name) : name).split("\\.")).map(s -> "`" + s + "`").collect(Collectors.joining("."));
     }
 
+    private static void validateName(String name) {
+        if(!NAME_PATTERN.matcher(name).matches())
+            throw new ORMQueryException("Invalid column name '" + name + "' (Use raw in case you know what you're doing)");
```
Comment (TimothyGillespie) [inline src/main/java/org/javawebstack/orm/query/QueryColumn.java:49]: This solves the other aspect of the issue of #14. If this branch is merged the issue can be closed.

File: src/main/java/org/javawebstack/orm/query/QueryCondition.java (hunk 2 above)
Comment (TimothyGillespie) [reply src/main/java/org/javawebstack/orm/query/QueryCondition.java:36]: With partially I only meant this code section. I did miss that one though. Thank you! I added the reference for this as well.

File: src/main/java/org/javawebstack/orm/query/QueryCondition.java (hunk 1 above)
Comment (TimothyGillespie) [reply src/main/java/org/javawebstack/orm/query/QueryCondition.java:11]: Your right about that. Enums do work a lot better for this. I think there will be few cases where it's not the case.
Either way, I will keep it in mind for my future code.

**Comment by TimothyGillespie** [comment]
I will review this tomorrow or later this evening.

**Review by TimothyGillespie — COMMENTED** [review]
See no issue with this merge request when #26 is merged or otherwise addressed.

**Comment by TimothyGillespie** [comment]
I changed #26 as discussed
